### ISSUE TITLE
Evento no detectado cuando se presionan varios controles a la vez

### ISSUE THREAD

**Issue by sergioherranzm** [sergioherranzm/this-is-not-battle-city#21]
si se pulsa dos controles a la vez, el tanque se moverá en la dirección del primer control, pero si se suelta este, la aceleración del tanque volverá a ser 0 a pesar de tener el segundo control todavía pulsado.

Habría que implementar un detector de multicontrol y de si un control se mantiene pulsado.

**Comment by luismiguelfeijoo** [comment]
El `event` [`keydown`](https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event) solo es capaz de reconocer la última tecla que has presionado.

Puedes registrar cada tecla presionada en un `objeto` o un `array` en el `keydown` (eliminar su registro en el `keyup`) y de esa forma controlar si tienes más de una presionada a la vez

**Comment by sergioherranzm** [comment]
arreglado con el uso de push a un array
