### ISSUE TITLE
Hacer que los fillText del canvas se escriban empezando por el lado izquierdo en vez de el derecho

### ISSUE THREAD

**Issue by sergioherranzm** [sergioherranzm/this-is-not-battle-city#23]
Title.

He pensado que con un translate, pero, ¿cómo sabes el ancho que va a ocupar el texto?

**Comment by luismiguelfeijoo** [comment]
Revisa estos metodos:

- [ctx.direction](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/direction)
- [ctx.textAlign](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textAlign)
